# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# plugins:

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - google1f891d7e1c888d33.html
  - CNAME

include:
  - _pages
  - _redirects

# Site settings
title: Site web personnel de Guillaume Meunier
long-title: Les travaux et publications de Guillaume Meunier
email: alliages@gmail.com
description: "Tout pour decarboner la construction, les travaux et publications de Guillaume Meunier"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guillaume-meunier.fr" # the base hostname & protocol for your site
timezone: Europe/London
year: 2024
start-year: 2024
sitemap: true

# Social networks
social-username:
  twitter: "@alliages"
  linkedin: "meunierguillaume"
  github: "alliages"
  medium: "@guillaume-meunier"
  instagram: "alliages"
  flickr: "alliages"
  joomeo: "alliages"

# Content
image_serve_path: "images" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

compress_html: # http://jch.penibelst.de/
  enabled: true # compress html
  clippings: all # clip safe tags
  comments: []
  endings: []
  #ignore:
    #envs: [local]
  blanklines: false # boolean - strip blank lines and breaks
  profile: false
  startings: []


# Structure
navigation:
  - title: Carbone
    url: /
  - title: A propos
    url: /about
  - title: Contact
    url: /contact

permalink: /:title/

# Configure site collections
collections:
  projects:
    output: true
    permalink: /projects/:path/


defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

